package lawFirm.mybatis.dao;

import java.util.List;
import lawFirm.mybatis.model.CaseClient;
import org.mybatis.cdi.Mapper;


@Mapper
public interface CaseClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CASE_CLIENT
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    int insert(CaseClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CASE_CLIENT
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    List<CaseClient> selectAll();
}