package lawFirm.mybatis.dao;

import java.util.List;
import lawFirm.mybatis.model.Client;
import org.mybatis.cdi.Mapper;


@Mapper
public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    Client selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    List<Client> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    int updateByPrimaryKey(Client record);
}