package lawFirm.mybatis.dao;

import java.util.List;
import lawFirm.mybatis.model.Lawyer;
import org.mybatis.cdi.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LawyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LAWYER
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LAWYER
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    int insert(Lawyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LAWYER
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    Lawyer selectByPrimaryKey(Long id);

    /**
     * Fetch a Lawyer along with their Law Cases
     */
    Lawyer selectLawyerWithCasesById(@Param("id") Long id);

    List<Lawyer> selectLawyersWithCases();

    Lawyer selectLawyerWithCases(@Param("id") Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LAWYER
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    List<Lawyer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LAWYER
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    int updateByPrimaryKey(Lawyer record);
}
