package lawFirm.mybatis.model;

public class CaseClient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CASE_CLIENT.CASE_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private Long caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CASE_CLIENT.CLIENT_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private Long clientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CASE_CLIENT.CASE_ID
     *
     * @return the value of PUBLIC.CASE_CLIENT.CASE_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public Long getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CASE_CLIENT.CASE_ID
     *
     * @param caseId the value for PUBLIC.CASE_CLIENT.CASE_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setCaseId(Long caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CASE_CLIENT.CLIENT_ID
     *
     * @return the value of PUBLIC.CASE_CLIENT.CLIENT_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CASE_CLIENT.CLIENT_ID
     *
     * @param clientId the value for PUBLIC.CASE_CLIENT.CLIENT_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }
}