package lawFirm.mybatis.model;

public class LawCase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAW_CASE.ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAW_CASE.DESCRIPTION
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAW_CASE.TITLE
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAW_CASE.LAWYER_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private Long lawyerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAW_CASE.ID
     *
     * @return the value of PUBLIC.LAW_CASE.ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAW_CASE.ID
     *
     * @param id the value for PUBLIC.LAW_CASE.ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAW_CASE.DESCRIPTION
     *
     * @return the value of PUBLIC.LAW_CASE.DESCRIPTION
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAW_CASE.DESCRIPTION
     *
     * @param description the value for PUBLIC.LAW_CASE.DESCRIPTION
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAW_CASE.TITLE
     *
     * @return the value of PUBLIC.LAW_CASE.TITLE
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAW_CASE.TITLE
     *
     * @param title the value for PUBLIC.LAW_CASE.TITLE
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAW_CASE.LAWYER_ID
     *
     * @return the value of PUBLIC.LAW_CASE.LAWYER_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public Long getLawyerId() {
        return lawyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAW_CASE.LAWYER_ID
     *
     * @param lawyerId the value for PUBLIC.LAW_CASE.LAWYER_ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setLawyerId(Long lawyerId) {
        this.lawyerId = lawyerId;
    }
}