package lawFirm.mybatis.model;

public class Lawyer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAWYER.ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAWYER.NAME
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAWYER.SPECIALIZATION
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    private String specialization;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAWYER.ID
     *
     * @return the value of PUBLIC.LAWYER.ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAWYER.ID
     *
     * @param id the value for PUBLIC.LAWYER.ID
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAWYER.NAME
     *
     * @return the value of PUBLIC.LAWYER.NAME
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAWYER.NAME
     *
     * @param name the value for PUBLIC.LAWYER.NAME
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAWYER.SPECIALIZATION
     *
     * @return the value of PUBLIC.LAWYER.SPECIALIZATION
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public String getSpecialization() {
        return specialization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAWYER.SPECIALIZATION
     *
     * @param specialization the value for PUBLIC.LAWYER.SPECIALIZATION
     *
     * @mbg.generated Sat Apr 12 23:15:16 EEST 2025
     */
    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }
}